import { Alert, Metric, TimeSlot, SessionType } from './types'
import { ScheduleResponse } from './types/schedule.types'

// Mock data
const mockAlerts: Alert[] = [
  {
    id: "1",
    type: "error",
    title: "CSV Upload Failed: rooms.csv",
    message: "Invalid format at row 15. Room capacity must be a positive integer.",
    actionLink: "#",
    actionText: "View Details",
  },
  {
    id: "2",
    type: "warning",
    title: "3 Teachers have no availability set",
    message: "These teachers will be scheduled based on default availability.",
    actionLink: "#",
    actionText: "View Teachers",
  },
  {
    id: "3",
    type: "success",
    title: "Schedule Generation Complete",
    message: '"Fall 2025 - Initial Draft" has been generated successfully.',
    actionLink: "#",
    actionText: "View Schedule",
  },
  {
    id: "4",
    type: "info",
    title: "System Maintenance",
    message: "Scheduled maintenance on May 20, 2025 from 2:00 AM to 4:00 AM.",
    actionLink: "#",
    actionText: "Learn More",
  },
]

const mockMetrics: Metric[] = [
  {
    id: "1",
    title: "Total Courses",
    value: 142,
    change: {
      type: "increase",
      value: "8.5% from last semester",
    },
    icon: "courses",
  },
  {
    id: "2",
    title: "Teachers",
    value: 56,
    change: {
      type: "no-change",
      value: "No change from last semester",
    },
    icon: "teachers",
  },
  {
    id: "3",
    title: "Rooms",
    value: 38,
    change: {
      type: "increase",
      value: "3 new rooms added",
    },
    icon: "rooms",
  },
  {
    id: "4",
    title: "Student Groups",
    value: 24,
    change: {
      type: "decrease",
      value: "2 less than last semester",
    },
    icon: "student-groups",
  },
]

// Current schedule data
// const mockCurrentSchedule = {
//   name: "Fall 2025 - Draft Available",
//   lastUpdated: "May 15, 2025, 10:30 AM",
// }
// export const mockScheduleData: ScheduleResponse = {
//   "scheduleId": "07d9e275-cb07-4b3e-b5e9-c184bd883228",
//   "sessions": [
//     {
//       "courseId": "course-001-L-G1",
//       "courseName": "Fundamental of Electrical Circuits and Electronics",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "13:30-15:00",
//       "day": "THURSDAY"
//     },
//     {
//       "courseId": "course-001-L-G2",
//       "courseName": "Fundamental of Electrical Circuits and Electronics",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "15:10-16:40",
//       "day": "MONDAY"
//     },
//     {
//       "courseId": "course-001-P-G1",
//       "courseName": "Fundamental of Electrical Circuits and Electronics",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "08:00-09:30",
//       "day": "MONDAY"
//     },
//     {
//       "courseId": "course-001-P-G2",
//       "courseName": "Fundamental of Electrical Circuits and Electronics",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "15:10-16:40",
//       "day": "TUESDAY"
//     },
//     {
//       "courseId": "course-002-L-G1",
//       "courseName": "Computer Architecture and Organization",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "08:00-09:30",
//       "day": "WEDNESDAY"
//     },
//     {
//       "courseId": "course-002-L-G2",
//       "courseName": "Computer Architecture and Organization",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "11:20-12:50",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-003-L-G1",
//       "courseName": "Web Design and Development",
//       "teacherId": "teacher-002",
//       "teacherName": "Natinael Wondimu",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "15:10-16:40",
//       "day": "WEDNESDAY"
//     },
//     {
//       "courseId": "course-003-L-G2",
//       "courseName": "Web Design and Development",
//       "teacherId": "teacher-002",
//       "teacherName": "Natinael Wondimu",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "09:40-11:10",
//       "day": "WEDNESDAY"
//     },
//     {
//       "courseId": "course-003-P-G1",
//       "courseName": "Web Design and Development",
//       "teacherId": "teacher-002",
//       "teacherName": "Natinael Wondimu",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "15:10-16:40",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-003-P-G2",
//       "courseName": "Web Design and Development",
//       "teacherId": "teacher-002",
//       "teacherName": "Natinael Wondimu",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "08:00-09:30",
//       "day": "THURSDAY"
//     },
//     {
//       "courseId": "course-004-L-G1",
//       "courseName": "Human Computer Interaction",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "13:30-15:00",
//       "day": "WEDNESDAY"
//     },
//     {
//       "courseId": "course-004-L-G2",
//       "courseName": "Human Computer Interaction",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "09:40-11:10",
//       "day": "MONDAY"
//     },
//     {
//       "courseId": "course-005-L-G1",
//       "courseName": "Fundamentals of Software Engineering",
//       "teacherId": "teacher-003",
//       "teacherName": "Nebiat Tekle",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "15:10-16:40",
//       "day": "THURSDAY"
//     },
//     {
//       "courseId": "course-005-L-G2",
//       "courseName": "Fundamentals of Software Engineering",
//       "teacherId": "teacher-003",
//       "teacherName": "Nebiat Tekle",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "13:30-15:00",
//       "day": "WEDNESDAY"
//     },
//     {
//       "courseId": "course-005-P-G1",
//       "courseName": "Fundamentals of Software Engineering",
//       "teacherId": "teacher-003",
//       "teacherName": "Nebiat Tekle",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y3-se-s1"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "11:20-12:50",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-005-P-G2",
//       "courseName": "Fundamentals of Software Engineering",
//       "teacherId": "teacher-003",
//       "teacherName": "Nebiat Tekle",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y3-se-s4"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "08:00-09:30",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-006-L-G1",
//       "courseName": "Software Project Management",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y4-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "15:10-16:40",
//       "day": "WEDNESDAY"
//     },
//     {
//       "courseId": "course-006-L-G2",
//       "courseName": "Software Project Management",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y4-ai"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "11:20-12:50",
//       "day": "WEDNESDAY"
//     },

//     {
//       "courseId": "course-006-L-G3",
//       "courseName": "Software Project Management",
//       "teacherId": "teacher-1",
//       "teacherName": "Abrham Gebremedhin",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y4-it"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "09:40-11:10",
//       "day": "THURSDAY"
//     },
//     {
//       "courseId": "course-007-L-G1",
//       "courseName": "Enterprise Application Development",
//       "teacherId": "teacher-002",
//       "teacherName": "Natinael Wondimu",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y4-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "11:20-12:50",
//       "day": "TUESDAY"
//     },
//     {
//       "courseId": "course-007-P-G1",
//       "courseName": "Enterprise Application Development",
//       "teacherId": "teacher-002",
//       "teacherName": "Natinael Wondimu",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y4-se-s1"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "11:20-12:50",
//       "day": "WEDNESDAY"
//     },
//     {
//       "courseId": "course-008-L-G1",
//       "courseName": "History of Ethiopia and the Horn",
//       "teacherId": "teacher-004",
//       "teacherName": "Amanuel Tadesse",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y4-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "15:10-16:40",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-008-L-G2",
//       "courseName": "History of Ethiopia and the Horn",
//       "teacherId": "teacher-004",
//       "teacherName": "Amanuel Tadesse",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y4-ai"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "11:20-12:50",
//       "day": "TUESDAY"
//     },
//     {
//       "courseId": "course-008-L-G3",
//       "courseName": "History of Ethiopia and the Horn",
//       "teacherId": "teacher-004",
//       "teacherName": "Amanuel Tadesse",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y4-cy"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "11:20-12:50",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-008-L-G4",
//       "courseName": "History of Ethiopia and the Horn",
//       "teacherId": "teacher-004",
//       "teacherName": "Amanuel Tadesse",
//       "classroomId": "classroom-002",
//       "classroomName": "NB112",
//       "classGroupIds": ["sg-y4-it"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "08:00-09:30",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-009-L-G1",
//       "courseName": "Machine Learning and Big Data",
//       "teacherId": "teacher-005",
//       "teacherName": "Bereket Haile",
//       "classroomId": "classroom-001",
//       "classroomName": "NB111",
//       "classGroupIds": ["sg-y4-se-s1"],
//       "sessionType": SessionType.LECTURE,
//       "timeslot": "09:40-11:10",
//       "day": "FRIDAY"
//     },
//     {
//       "courseId": "course-009-P-G1",
//       "courseName": "Machine Learning and Big Data",
//       "teacherId": "teacher-005",
//       "teacherName": "Bereket Haile",
//       "classroomId": "classroom-004",
//       "classroomName": "NB114",
//       "classGroupIds": ["sg-y4-se-s1"],
//       "sessionType": SessionType.LAB,
//       "timeslot": "11:20-12:50",
//       "day": "THURSDAY"
//     }
//   ]

// };

export const mockTimeslots: TimeSlot[] = [
  {
    timeslotId: "ts001",
    code: "0800_0900",
    label: "08:00-09:00",
    startTime: "08:00",
    endTime: "09:00",
    order: 1,
  },
  {
    timeslotId: "ts002",
    code: "0900_1000",
    label: "09:00-10:00",
    startTime: "09:00",
    endTime: "10:00",
    order: 2,
  },
  {
    timeslotId: "ts003",
    code: "1000_1100",
    label: "10:00-11:00",
    startTime: "10:00",
    endTime: "11:00",
    order: 3,
  },
  {
    timeslotId: "ts004",
    code: "1100_1200",
    label: "11:00-12:00",
    startTime: "11:00",
    endTime: "12:00",
    order: 4,
  },
  {
    timeslotId: "ts005",
    code: "1200_1300",
    label: "12:00-13:00",
    startTime: "12:00",
    endTime: "13:00",
    order: 5,
  },
  {
    timeslotId: "ts006",
    code: "1300_1400",
    label: "13:00-14:00",
    startTime: "13:00",
    endTime: "14:00",
    order: 6,
  },
  {
    timeslotId: "ts007",
    code: "1400_1500",
    label: "14:00-15:00",
    startTime: "14:00",
    endTime: "15:00",
    order: 7,
  },
  {
    timeslotId: "ts008",
    code: "1500_1600",
    label: "15:00-16:00",
    startTime: "15:00",
    endTime: "16:00",
    order: 8,
  },
  {
    timeslotId: "ts009",
    code: "1600_1700",
    label: "16:00-17:00",
    startTime: "16:00",
    endTime: "17:00",
    order: 9,
  },
  {
    timeslotId: "ts010",
    code: "1700_1800",
    label: "17:00-18:00",
    startTime: "17:00",
    endTime: "18:00",
    order: 10,
  },
]