"use client";

import { useState } from "react";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  User,
  Mail,
  GraduationCap,
  Building,
  Plus,
  Search,
  Edit,
  Trash2,
} from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import useAuthStore from "@/lib/stores/auth-store";
import { useTeacherStore } from "@/lib/stores/teacher.store";
import { useDepartmentStore } from "@/lib/stores/department.store";
import { ConfirmDeleteDialog } from "@/components/ui/confirm-delete";

export default function TeachersPage() {
  const { isAuthenticated } = useAuthStore();
  const { teachers, fetchTeachers, addTeacher, updateTeacher, deleteTeacher } =
    useTeacherStore();
  const { departments, fetchDepartments } = useDepartmentStore();
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [departmentFilter, setDepartmentFilter] = useState("all");
  const [selectedTeacher, setSelectedTeacher] = useState<string | null>(null);
  const [isConfirmDeleteDialogOpen, setIsConfirmDeleteDialogOpen] =
    useState(false);

  const initialFormData = {
    firstName: "",
    lastName: "",
    email: "",
    departmentId: "",
  };

  const [formData, setFormData] = useState(initialFormData);
  const router = useRouter();

  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/");
    }
  }, [isAuthenticated, router]);

  if (!isAuthenticated) {
    return null;
  }

  useEffect(() => {
    fetchDepartments();
    fetchTeachers();
  }, [fetchDepartments, fetchTeachers]);

  const handleAddTeacher = () => {
    addTeacher({
      userId: "", // Will be generated by backend
      departmentId: formData.departmentId,
    });
    setFormData(initialFormData);
    setIsAddDialogOpen(false);
  };

  const [filteredTeachers, setFilteredTeachers] = useState(teachers);
  useEffect(() => {
    let newFiltered = teachers.filter(
      (teacher) =>
        `${teacher.user.firstName} ${teacher.user.lastName}`
          .toLowerCase()
          .includes(searchQuery.toLowerCase()) &&
        (departmentFilter === "all" ||
          teacher.department.deptId === departmentFilter)
    );
    setFilteredTeachers(newFiltered);
  }, [searchQuery, departmentFilter, teachers]);

  const handleEditTeacher = () => {
    if (selectedTeacher) {
      updateTeacher(selectedTeacher, {
        departmentId: formData.departmentId,
      });
      setIsEditDialogOpen(false);
    }
  };

  const openConfirmDeleteDialog = (id: string) => {
    setSelectedTeacher(id);
    setIsConfirmDeleteDialogOpen(true);
  };

  const handleConfirmDelete = () => {
    if (selectedTeacher) {
      deleteTeacher(selectedTeacher);
    }
  };

  const resetFormData = () => {
    setFormData(initialFormData);
    setSelectedTeacher(null);
  };

  const openEditDialog = (id: string) => {
    const teacher = teachers.find((t) => t.teacherId === id);
    if (teacher) {
      setSelectedTeacher(id);
      setFormData({
        firstName: teacher.user.firstName,
        lastName: teacher.user.lastName,
        email: teacher.user.email,
        departmentId: teacher.department.deptId,
      });
      setIsEditDialogOpen(true);
    }
  };

  return (
    <DashboardLayout title="Teachers">
      <div className="space-y-6">
        {/* Header Section */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 pb-2 border-b">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Teachers</h1>
            <p className="text-muted-foreground text-sm">
              Manage teacher information and departments
            </p>
          </div>
          <Button
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold shadow-sm"
            onClick={() => setIsAddDialogOpen(true)}
          >
            <Plus className="mr-2 h-4 w-4" />
            Add Teacher
          </Button>
        </div>

        {/* Search and Filter Section */}
        <div className="flex flex-col md:flex-row md:items-center gap-3 md:gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
            <Input
              type="search"
              placeholder="Search teachers..."
              className="w-full pl-10 py-2 rounded-md border-gray-200"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <Select
            onValueChange={(val) => setDepartmentFilter(val)}
            value={departmentFilter}
          >
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="All Departments" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Departments</SelectItem>
              {departments.map((dept) => (
                <SelectItem key={dept.deptId} value={dept.deptId}>
                  {dept.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Table Section */}
        <div className="rounded-xl border bg-white shadow-sm overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>TEACHER</TableHead>
                <TableHead>EMAIL</TableHead>
                <TableHead>DEPARTMENT</TableHead>
                <TableHead className="text-right">ACTIONS</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredTeachers.map((teacher) => (
                <TableRow key={teacher.teacherId} className="hover:bg-muted/40">
                  <TableCell className="flex items-center gap-3 font-medium">
                    <span className="inline-flex items-center justify-center h-8 w-8 rounded-md bg-blue-100 text-blue-600">
                      <User color="currentColor" className="w-4 h-4" />
                    </span>
                    <div>
                      <div className="font-semibold leading-tight">
                        {teacher.user.firstName} {teacher.user.lastName}
                      </div>
                      <div className="text-xs text-muted-foreground">
                        ID: {teacher.teacherId}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <Mail className="h-4 w-4 text-gray-500" />
                      <span>{teacher.user.email}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <span>{teacher.department.name}</span>
                    </div>
                  </TableCell>
                  
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button
                        variant="edit"
                        size="icon"
                        className="hover:bg-indigo-100"
                        onClick={() => openEditDialog(teacher.teacherId)}
                        aria-label="Edit"
                      >
                        <Edit color="currentColor" className="w-5 h-5" />
                      </Button>
                      <Button
                        variant="delete"
                        size="icon"
                        className="hover:bg-red-100"
                        onClick={() =>
                          openConfirmDeleteDialog(teacher.teacherId)
                        }
                        aria-label="Delete"
                      >
                        <Trash2
                          color="currentColor"
                          strokeWidth={2}
                          className="w-5 h-5"
                        />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>

      {/* Add/Edit Teacher Dialog */}
      <Dialog
        open={isAddDialogOpen || isEditDialogOpen}
        onOpenChange={(open) => {
          if (!open) {
            setIsAddDialogOpen(false);
            setIsEditDialogOpen(false);
            resetFormData();
          }
        }}
      >
        <DialogContent className="max-w-2xl w-full">
          <DialogHeader>
            <DialogTitle>
              {isAddDialogOpen ? "Add New Teacher" : "Edit Teacher"}
            </DialogTitle>
          </DialogHeader>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (isAddDialogOpen) handleAddTeacher();
              if (isEditDialogOpen) handleEditTeacher();
            }}
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 p-4 mt-5">
              <div className="space-y-2 flex flex-col gap-3">
                <Label htmlFor="firstName">First Name</Label>
                <Input
                  id="firstName"
                  placeholder="e.g., John"
                  value={formData.firstName}
                  onChange={(e) =>
                    setFormData({ ...formData, firstName: e.target.value })
                  }
                  required
                />
              </div>
              <div className="space-y-2 flex flex-col gap-3">
                <Label htmlFor="lastName">Last Name</Label>
                <Input
                  id="lastName"
                  placeholder="e.g., Doe"
                  value={formData.lastName}
                  onChange={(e) =>
                    setFormData({ ...formData, lastName: e.target.value })
                  }
                  required
                />
              </div>
              <div className="space-y-2 flex flex-col gap-3 md:col-span-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="e.g., john.doe@example.com"
                  value={formData.email}
                  onChange={(e) =>
                    setFormData({ ...formData, email: e.target.value })
                  }
                  required
                />
              </div>
              <div className="space-y-2 flex flex-col gap-3 md:col-span-2">
                <Label htmlFor="department">Department</Label>
                <Select
                  value={formData.departmentId}
                  onValueChange={(value) =>
                    setFormData({ ...formData, departmentId: value })
                  }
                  required
                >
                  <SelectTrigger id="department">
                    <SelectValue placeholder="Select department..." />
                  </SelectTrigger>
                  <SelectContent>
                    {departments.map((dept) => (
                      <SelectItem key={dept.deptId} value={dept.deptId}>
                        {dept.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <DialogFooter className="mt-2">
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  setIsAddDialogOpen(false);
                  setIsEditDialogOpen(false);
                }}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                className="bg-indigo-600 hover:bg-indigo-700"
              >
                {isAddDialogOpen ? "Create Teacher" : "Save Changes"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <ConfirmDeleteDialog
        open={isConfirmDeleteDialogOpen}
        onConfirm={handleConfirmDelete}
        onOpenChange={setIsConfirmDeleteDialogOpen}
      />
    </DashboardLayout>
  );
}
